### PR TITLE
apkutils: Add certificate tests, different checksum algorithms 

### PR DESCRIPTION
**Pull request by defer**
This patch adds support for multiple checksum algorithms rather than
just returning md5. APK.get_certs() behaves the same way, but it can now
take an optional 'digestalgo' parameter. Digest algorithms are cached
per algorithm.

In the process of testing this, I also found that the library can't
handle some apps that add data files to META-INF (i.e. any kotlin app
will do this) because they try to interpret said data files as
certificates. The patch instead uses the AOSP guessing logic to get the
certificate name (must be in META-INF and be named *.RSA or *.DSA).
There's also a sample kotlin app and test case.

### CODE REVIEW

**Comment by mikusjelly** [comment]
@defer If possible, please give me the sample(or it's md5), thanks.

**Comment by defer** [comment]
I'll add some tests, I'll also need to add other hash types.

**Comment by defer** [comment]
Added multi-digest support and tests for both cases.

**Comment by defer** [comment]
Would you consider releasing a version containing these? I want to use them in production and would love to avoid using forked versions.

**Comment by mikusjelly** [comment]
OK. Now you can get the source code from the [Releases](https://github.com/mikusjelly/apkutils/releases) page.

**Pull request merged**
