### PR TITLE
Patch

### PR DESCRIPTION
**Pull request by codeskyblue**
- Add a simple APKParser UI with tkinter

image

- add manifest property, so you can writh code like

```python
m = apkutils.APK("some.apk").manifest
print("packageName:", m.package_name)
print("version_code:", m.version_code)
print("main_activity:", m.main_activity)
```

### CODE REVIEW

**Comment by codeskyblue** [comment]
Hope can be merged

**Comment by codeskyblue** [comment]
when `__VERSION__` in `__init__.py`, pip install will got the following error.

```
Obtaining file:///Users/codeskyblue/Workspace/apkutils
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/codeskyblue/Workspace/apkutils/setup.py", line 3, in <module>
        from apkutils import __VERSION__
      File "/Users/codeskyblue/Workspace/apkutils/apkutils/__init__.py", line 7, in <module>
        import xmltodict
    ModuleNotFoundError: No module named 'xmltodict'
```

So I also modified here.

**Comment by mikusjelly** [comment]
Thanks your request, but this is a library, not a tool.
I think you can release your tool as a new project.

**Comment by codeskyblue** [comment]
OK, thanks you for making this awesome project. I will make another project.

**Comment by codeskyblue** [comment]
BTW: this is an error, I think you should know
image

**Comment by mikusjelly** [comment]
Because your OS don't have [xmltodict](https://pypi.org/project/xmltodict/), you can 
1. `pip install xmltodict`
2. or run `pip install -U apkutils` again, it will be auto install .

**Comment by codeskyblue** [comment]
it's not right

**Comment by mikusjelly** [comment]
```
$ pip uninstall apkutils                               
Uninstalling apkutils-0.5.3:
  Would remove:
    /usr/local/miniconda3/lib/python3.6/site-packages/apkutils.egg-link
Proceed (y/n)? y
  Successfully uninstalled apkutils-0.5.3
$ pip uninstall xmltodict                                                 
Uninstalling xmltodict-0.11.0:
  Would remove:
    /usr/local/miniconda3/lib/python3.6/site-packages/xmltodict-0.11.0.dist-info/*
    /usr/local/miniconda3/lib/python3.6/site-packages/xmltodict.py
Proceed (y/n)? y
  Successfully uninstalled xmltodict-0.11.0
$ pip install -U apkutils                 
Collecting apkutils
  Downloading https://files.pythonhosted.org/packages/54/2d/b4d4068db1d1e150ae390379cbc5e0d4e545da85054c678ac71be4f75f5e/apkutils-0.5.3-py3-none-any.whl (68kB)
    100% |████████████████████████████████| 71kB 162kB/s
Collecting xmltodict (from apkutils)
  Downloading https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: cigam in /usr/local/miniconda3/lib/python3.6/site-packages (from apkutils) (0.0.3)
Requirement already satisfied, skipping upgrade: pyelftools in /usr/local/miniconda3/lib/python3.6/site-packages (from apkutils) (0.24)
Installing collected packages: xmltodict, apkutils
Successfully installed apkutils-0.5.3 xmltodict-0.12.0
```

**Comment by codeskyblue** [comment]
I tested on windows, linux. mac. It seems that is only happends on my mac.

**Comment by mikusjelly** [comment]
My mac is worked.

**Comment by codeskyblue** [comment]
never mind. Canot reproduce anymore

**Pull request closed without merging**
